version: "3.7"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongo"
      MONGO_INITDB_ROOT_PASSWORD: "mongo"
      MONGO_INITDB_DATABASE: "otus"
    command: mongod --auth
    volumes:
      - ./database:/mongo-seed
    networks:
      - code-challenge

  graphql-api:
    container_name: graphql-api
    build: .
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      DATABASE_HOST: mongodb
      DATABASE_NAME: otus
      DATABASE_PASSWORD: mongo
      DATABASE_PORT: 27017
      DATABASE_USER: mongo
      API_PORT: 8080
    command: /usr/bin/java -jar /app.jar
    networks:
      - code-challenge

networks:
  code-challenge:
    name: code-challenge
