---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.eks.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  type: ClusterIP
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: mongodb

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.eks.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
      - args:
        - mongod
        - --auth
        env:
        - name: MONGO_INITDB_DATABASE
          value: otus
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: mongo
        - name: MONGO_INITDB_ROOT_USERNAME
          value: mongo
        image: docker.io/eschizoid/mongodb:otus
        name: mongodb
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
status: {}
